{% set name = "apache-airflow-providers-asana" %}
{% set version = "2.11.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_asana-{{ version }}.tar.gz
  sha256: e8743d90974543b011cca4dffc420809699340b567e92bdb064a4a2a4d2f9a8c

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.11.0
    - apache-airflow-providers-common-compat >=1.8.0
    - python-asana >=5.0.0

test:
  imports:
    - airflow.providers.asana
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-asana for Apache Airflow
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-asana/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
